# @rootUrl = localhost:5245
@rootUrl = https://apim-dev-tag.azure-api.net
@firstName = Robbie
@surname = Whiting

POST {{rootUrl}}/api/customer HTTP/1.1
Ocp-Apim-Subscription-Key: c7259a70c86b41abbb767b9ae29dab15
Content-Type: application/json

{
    "firstName": "{{firstName}}",
    "surname": "{{surname}}"
}